# Generated by Django 6.0.7 on 2026-08-02 07:52

import accounts.models.avatar
import accounts.validators.avatar
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAvatarModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the avatar.', primary_key=True, serialize=False)),
                ('image', models.ImageField(help_text='Avatar image.', upload_to=accounts.models.avatar.avatar_upload_path, validators=[accounts.validators.avatar.avatar_validator])),
                ('is_primary', models.BooleanField(db_index=True, default=False, help_text="Whether this avatar is the user's primary avatar.")),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Avatar upload time.')),
                ('user', models.ForeignKey(help_text='Owner of this avatar.', on_delete=django.db.models.deletion.CASCADE, related_name='avatars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
