# Generated by Django 6.0.7 on 2026-08-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useravatarmodel'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='useravatarmodel',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('user',), name='unique_primary_avatar_per_user'),
        ),
    ]
