# Generated by Django 6.0.7 on 2026-08-19 20:38

import core.validators.phone_number
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the user.', primary_key=True, serialize=False)),
                ('phone_number', models.CharField(db_index=True, error_messages={'unique': 'A user with this phone number already exists.'}, help_text='Iranian mobile number in the format 09XXXXXXXXX.', max_length=11, unique=True, validators=[core.validators.phone_number.model_phone_number_validator])),
                ('first_name', models.CharField(blank=True, default='', help_text="User's first name.", max_length=150)),
                ('last_name', models.CharField(blank=True, default='', help_text="User's last name.", max_length=150)),
                ('status', models.CharField(choices=[('active', 'Active'), ('banned', 'Banned'), ('inactive', 'Inactive')], db_index=True, default='active', help_text='Current account status.', max_length=20)),
                ('role', models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('superuser', 'Superuser')], db_index=True, default='user', help_text='User role used for authorization.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the user was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the user was last updated.')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ('-created_at',),
            },
        ),
    ]
