# Generated by Django 6.0.7 on 2026-08-27 20:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginHistoryModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text="IP address of the user's device.", null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Raw User-Agent string sent by the client.', null=True)),
                ('device', models.CharField(blank=True, help_text='Device type, such as Mobile, Tablet, or PC.', max_length=50, null=True)),
                ('device_family', models.CharField(blank=True, help_text='Device family or model reported by the User-Agent.', max_length=100, null=True)),
                ('browser', models.CharField(blank=True, help_text='Browser name.', max_length=100, null=True)),
                ('browser_version', models.CharField(blank=True, help_text='Browser version.', max_length=100, null=True)),
                ('operating_system', models.CharField(blank=True, help_text='Operating system name.', max_length=100, null=True)),
                ('operating_system_version', models.CharField(blank=True, help_text='Operating system version.', max_length=100, null=True)),
                ('country', models.CharField(blank=True, help_text="Country resolved from the client's IP address.", max_length=100, null=True)),
                ('country_code', models.CharField(blank=True, help_text='ISO 3166-1 alpha-2 country code.', max_length=2, null=True)),
                ('region', models.CharField(blank=True, help_text="Region or state resolved from the client's IP address.", max_length=100, null=True)),
                ('city', models.CharField(blank=True, help_text="City resolved from the client's IP address.", max_length=100, null=True)),
                ('latitude', models.FloatField(blank=True, help_text="Approximate latitude resolved from the client's IP address.", null=True)),
                ('longitude', models.FloatField(blank=True, help_text="Approximate longitude resolved from the client's IP address.", null=True)),
                ('is_successful', models.BooleanField(default=True, help_text='Whether the login attempt was successful.')),
                ('failure_reason', models.TextField(blank=True, help_text='Reason for the login failure.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='User associated with this login attempt.', on_delete=django.db.models.deletion.CASCADE, related_name='login_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Login History',
                'verbose_name_plural': 'Login Histories',
                'db_table': 'login_histories',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='login_history_user_date_idx'), models.Index(fields=['ip_address', '-created_at'], name='login_history_ip_date_idx'), models.Index(fields=['is_successful', '-created_at'], name='login_history_status_date_idx')],
            },
        ),
    ]
