class ErrorCode:
    """
    Standard API error codes.
    """

    # General
    VALIDATION_ERROR = "VALIDATION_ERROR"
    SERVER_ERROR = "SERVER_ERROR"
    DATABASE_ERROR = "DATABASE_ERROR"

    # Authentication
    NOT_AUTHENTICATED = "NOT_AUTHENTICATED"
    PERMISSION_DENIED = "PERMISSION_DENIED"

    # Resources
    NOT_FOUND = "NOT_FOUND"

    # User
    USERNAME_REQUIRED = "USERNAME_REQUIRED"
    USERNAME_ALREADY_EXISTS = "USERNAME_ALREADY_EXISTS"
    USERNAME_INVALID = "USERNAME_INVALID"

    EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS"
    EMAIL_INVALID = "EMAIL_INVALID"

    PHONE_ALREADY_EXISTS = "PHONE_ALREADY_EXISTS"
    PHONE_INVALID = "PHONE_INVALID"

    # Rate limit
    TOO_MANY_REQUESTS = "TOO_MANY_REQUESTS"
