class ErrorCode:

    SUCCESS = "SUCCESS"

    # Authentication
    PERMISSION_DENIED = "PERMISSION_DENIED"
    NOT_AUTHENTICATED = "NOT_AUTHENTICATED"
    AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR"

    ACCOUNT_DISABLED = "ACCOUNT_DISABLED"
    ACCOUNT_NOT_FOUND = "ACCOUNT_NOT_FOUND"

    # Server
    NOT_FOUND = "NOT_FOUND"
    THROTTLED = "THROTTLED"
    SERVER_ERROR = "SERVER_ERROR"
    NETWORK_ERROR = "NETWORK_ERROR"

    # Validation
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"

    VALIDATION_ERROR = "VALIDATION_ERROR"

    LAST_NAME_TOO_SHORT = "LAST_NAME_TOO_SHORT"
    FIRST_NAME_TOO_SHORT = "FIRST_NAME_TOO_SHORT"
    INVALID_PHONE_NUMBER = "INVALID_PHONE_NUMBER"

    EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS"
    PHONE_ALREADY_EXISTS = "PHONE_ALREADY_EXISTS"
    USERNAME_ALREADY_EXISTS = "USERNAME_ALREADY_EXISTS"
