from rest_framework import serializers

from authentication.models import LoginHistoryModel


class LoginHistorySerializer(serializers.ModelSerializer):
    """
    Serializer for exposing authenticated user's login history.

    This serializer is strictly read-only. Login history records are
    generated by the authentication system and cannot be created,
    modified, or deleted through the API.
    """

    user = serializers.PrimaryKeyRelatedField(
        read_only=True,
    )

    class Meta:
        model = LoginHistoryModel

        fields = (
            # ----------------------------------------------------------
            # Identity
            # ----------------------------------------------------------
            "id",
            "user",
            # ----------------------------------------------------------
            # Authentication
            # ----------------------------------------------------------
            "is_successful",
            "failure_reason",
            # ----------------------------------------------------------
            # Network
            # ----------------------------------------------------------
            "ip_address",
            # ----------------------------------------------------------
            # User Agent
            # ----------------------------------------------------------
            "user_agent",
            # ----------------------------------------------------------
            # Device
            # ----------------------------------------------------------
            "device",
            "device_family",
            # ----------------------------------------------------------
            # Browser
            # ----------------------------------------------------------
            "browser",
            "browser_version",
            # ----------------------------------------------------------
            # Operating System
            # ----------------------------------------------------------
            "operating_system",
            "operating_system_version",
            # ----------------------------------------------------------
            # Location
            # ----------------------------------------------------------
            "country",
            "country_code",
            "region",
            "city",
            "latitude",
            "longitude",
            # ----------------------------------------------------------
            # Timestamps
            # ----------------------------------------------------------
            "created_at",
            "updated_at",
        )

        read_only_fields = fields
